#!/bin/sh
#
# Developer overlay install for libpcp<foo>
#

# need to get the pcp.conf usewd in the build, not the
# installed one
#
if [ ! -f ../../../src/include/pcp.conf ]
then
    echo "Arrgh: ../../../src/include/pcp.conf missing"
    exit 1
fi
PCP_CONF=../../../src/include/pcp.conf

if [ ! -f /etc/pcp.env ]
then
    echo "Arrgh: ../../../src/include/pcp.env missing"
    exit 1
fi

. /etc/pcp.env

iam="`pwd | sed -e 's;/src$;;' -e's;.*/\(.*\);\1;'`"

if ! make
then
    echo "Arrgh: make failed"
    exit 1
fi

case "`echo $iam.so.*`"
in
    *\ *)
	echo "Arrgh: more than one .so.*: `echo $iam.so.*`"
	exit 1
	;;
esac
dso_ver=`echo "$iam".so.* | sed -e 's/.*\.so\.//'`

if ! sudo make install
then
    echo "Arrgh: sudo make install failed"
    exit 1
fi

pkg_dir="`pkg-config --variable=libdir $iam 2>/dev/null`"
if [ -z "$pkg_dir" ]
then
    echo "Arrgh: no libdir from pkg-config"
    exit 1
fi
echo "Debug: pkg-config libdir: $pkg_dir"
echo "Debug: PCP build libdir: $PCP_LIB_DIR"

if [ "$pkg_dir" != "$PCP_LIB_DIR" ]
then
    if ! [ -f $PCP_LIB_DIR/$iam.so.$dso_ver ]
    then
	echo "Arrgh: no $PCP_LIB_DIR/$iam.so.$dso_ver"
	exit 1
    fi
    if ! [ -f "$pkg_dir"/$iam.so.$dso_ver ]
    then
	echo "Arrgh: no $pkg_dir/$iam.so.$dso_ver"
	exit 1
    fi
    if cmp $PCP_LIB_DIR/$iam.so.$dso_ver "$pkg_dir"/$iam.so.$dso_ver >/dev/null
    then
	echo "Warning: $PCP_LIB_DIR/$iam.so.$dso_ver and $pkg_dir/$iam.so.$dso_ver already the same?"
	ls -l $PCP_LIB_DIR/$iam.so.$dso_ver "$pkg_dir"/$iam.so.$dso_ver
    else
	sudo cp $PCP_LIB_DIR/$iam.so.$dso_ver "$pkg_dir"/$iam.so.$dso_ver
	echo "Info: updated $pkg_dir/$iam.so.$dso_ver"
    fi
else
    echo "Info: pkg-config and GNUmakefile agree on location for $iam.so.$dso_ver, nothing else to be done"
fi

exit 0

